### PR TITLE
Align the Three images of the admins in the Readme file

### LINKED ISSUE #2: Align the Three images of the admins in the readme file
In Redme file three admin's pics are in three different lines try to keep them in a single line side by side
* Pull request to be created in the **develop** branch

### PR DESCRIPTION
**Pull request by subh0x-alt**
Aligned the Project Admin Images to same line.

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
Please give small gaps after each image

**Review by subh0x-alt — COMMENTED** [review]
@ayan-biswas0412 I think I have made the required changes, please review.

**Comment by ayan-biswas0412** [comment]
Yes your PR has been already merged, please follow the slack and keep updated with the issues , a proposal alongwith timeline for the detailed project layout has been already posted in slack.

**Review by ayan-biswas0412 — COMMENTED** [review]
Nice work

**Pull request merged**
